"""Original, redistributable NROM diagnostic: checkerboard, pulse, pad mailbox.
No Nintendo/game assets. Generated bytes are derived solely from code below.
"""
from pathlib import Path
import argparse


def make_rom(prg_banks=1, test_rom_write=False, prologue=b''):
    code = bytearray()
    labels, fixups = {}, []
    def emit(*values): code.extend(values)
    def write(address, value): emit(0xa9, value, 0x8d, address & 255, address >> 8)
    def label(name): labels[name] = len(code)
    def branch(op, name): emit(op, 0); fixups.append((len(code)-1, name, False))
    def jump(name): emit(0x4c, 0, 0); fixups.append((len(code)-2, name, True))
    emit(0x78, 0xd8, 0xa2, 0xff, 0x9a)  # SEI, CLD, LDX #ff, TXS
    if test_rom_write:
        write(0x8000, 0)  # NROM has no mapper register; this must be ignored.
    write(0x2000, 0); write(0x2001, 0); write(0x4017, 0x40)
    code.extend(prologue)
    emit(0xa9, 0x5a, 0x85, 0x00)  # CPU diagnostic mailbox
    write(0x2006, 0x3f); write(0x2006, 0x00)
    for value in (0x0f, 0x21, 0x30, 0x16): write(0x2007, value)
    write(0x2005, 0); write(0x2005, 0)
    write(0x4015, 1); write(0x4000, 0xbf)
    write(0x4002, 0xfd); write(0x4003, 0x08)
    write(0x2001, 0x0a)
    label('poll')
    write(0x4016, 1); write(0x4016, 0)
    emit(0xa9, 0, 0x85, 2, 0xa2, 8)  # serialize into temporary $02
    label('bit')
    emit(0xad, 0x16, 0x40, 0x4a, 0x66, 2, 0xca)  # read; LSR A; ROR $02; DEX
    branch(0xd0, 'bit')
    emit(0xa5, 2, 0x85, 1)  # publish only a complete pad sample to $01
    jump('poll')
    for off, name, absolute in fixups:
        value = labels[name] + 0x8000 if absolute else labels[name] - (off+1)
        if absolute: code[off:off+2] = value.to_bytes(2, 'little')
        else:
            assert -128 <= value <= 127
            code[off] = value & 255
    prg = bytearray([0xea]) * (prg_banks*16384)
    prg[:len(code)] = code
    prg[-6:] = b'\x00\x80' * 3
    chr_data = bytearray(8192)
    chr_data[:8] = bytes([0xaa,0x55]*4)
    chr_data[8:16] = bytes([0,0,0xff,0xff]*2)
    return b'NES\x1a' + bytes([prg_banks,1]) + bytes(10) + prg + chr_data


def make_cnrom_rom(prg_banks=2, chr_banks=2, final_bank=0, mirroring=0):
    """Self-check all eight 1 KiB pages, bank aliases and read-only CHR/PRG.

    Failure halts with $00=0xe1; success reaches the normal $00=0x5a test.
    No conflict emulation is the port's explicit legacy-iNES policy.
    """
    code=bytearray()
    def write(address,value): code.extend((0xa9,value,0x8d,address&255,address>>8))
    def check(expected):
        # CMP #expected; BEQ success; LDA #e1; STA $00; BNE self
        code.extend((0xc9,expected,0xf0,6,0xa9,0xe1,0x85,0,0xd0,0xfe))
    def read_chr(address):
        write(0x2006,address>>8);write(0x2006,address&255)
        code.extend((0xad,7,0x20,0xad,7,0x20))  # discard buffered read
    def verify(bank):
        for page in range(8):
            address=page*1024+31
            read_chr(address);check(0x40+bank*8+page)
            write(0x2006,address>>8);write(0x2006,address&255)
            write(0x2007,0xee)  # must not modify CHR-ROM, including bank > 0
            read_chr(address);check(0x40+bank*8+page)
    verify(0)  # power-on bank
    for index,value in enumerate((3,0,2,1,0xff,0xfe,0x80,0xfd)):
        # Include both endpoints and every CPU 8 KiB region.
        write((0x8000,0x9fff,0xa000,0xc000,0xe000,0xffff)[index%6],value)
        verify(value & (chr_banks-1))
        code.extend((0xad,0,0x80));check(0x78)  # original SEI is unchanged
        if prg_banks==1:
            code.extend((0xad,0,0xc0));check(0x78)  # 16 KiB PRG mirror
    write(0x8000,final_bank)
    result=bytearray(make_rom(prg_banks,prologue=code))
    result[5]=chr_banks;result[6]=0x30|mirroring
    del result[16+prg_banks*16384:]
    for bank in range(chr_banks):
        data=bytearray(8192)
        # Distinct visible tile 0 for each bank.
        data[:8]=bytes([0xff if bank&1 else 0x55])*8
        data[8:16]=bytes([0xff if bank&2 else 0])*8
        for page in range(8): data[page*1024+31]=0x40+bank*8+page
        result.extend(data)
    return bytes(result)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(make_rom())
